# Bag Of Words (BoW)  
* Algo to convert text into Numerical representation
* Bag of words (a.k.a. BOW) is a technique used for text representation in natural language processing. In this NLP tutorial, we will go over how a bag of words works and also write some code for email classification that uses a bag of words and the Naive Bayes classifier in machine learning.

In [4]:
# %pip install pandas
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('spam.csv')
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
print(df.Category.value_counts()) 
# So, Firstly let's convert the Category column (As it has only 2 distinct value) into a simple Numerical representation of 0 and 1


# Instead of using lambda funtion we can also use below function
def get_spam_number(x):  # and call this particular function from apply(get_spam_number)
    if x=='spam':
        return 1
    return 0

# Making a new column named (spam) 
df['spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)
# df['spam'] = df['Category'].apply(get_spam_number)

print(f"Shape of the given dataframe : {df.shape}")
df.head()

Category
ham     4825
spam     747
Name: count, dtype: int64
Shape of the given dataframe : (5572, 3)

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [7]:
# Now spliting the data into Test-Train
# %pip install scikit-learn
from sklearn.model_selection import train_test_split

# The reason of 
X_train,X_test,y_train,y_test = train_test_split(df.Message,df.spam,test_size=0.2)

* Here X is capital bcz there can be more than one Dependent Variables so it's a standard way to represent by captical X
* And y is small as there is single Independent Variable.

In [8]:
X_train.shape

(4457,)

In [9]:
X_train.head()

2118    Wish u many many returns of the day.. Happy bi...
150                        Sindu got job in birla soft ..
2784         Just arrived, see you in a couple days &lt;3
3370    Sorry i've not gone to that place. I.ll do so ...
274                 Usf I guess, might as well take 1 car
Name: Message, dtype: str

In [10]:
X_test.shape

(1115,)

In [11]:
X_test.head()

4573                       Omg how did u know what I ate?
5123                       Hi Chikku, send some nice msgs
1060    EASTENDERS TV Quiz. What FLOWER does DOT compa...
4211    No da:)he is stupid da..always sending like th...
5326                           What makes you most happy?
Name: Message, dtype: str

In [12]:
y_train.head()

2118    0
150     0
2784    0
3370    0
274     0
Name: spam, dtype: int64

In [13]:
y_test.head()

4573    0
5123    0
1060    1
4211    0
5326    0
Name: spam, dtype: int64

In [15]:
# Converting the X_train from Text Representation to Vector so that we can feed that into our ML model
from sklearn.feature_extraction.text import CountVectorizer # We are using Bag Of Words Algo

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values) # X_train_cv => cv stands for countVectorized
print(X_train_cv.toarray())
X_train_cv.shape # It means we have 7753 unique words in our vocabulary

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

(4457, 7744)

In [16]:
v.vocabulary_ # By this we can see all the unique words in our made vocabulary

{'wish': 7543,
 'many': 4353,
 'returns': 5750,
 'of': 4889,
 'the': 6817,
 'day': 2193,
 'happy': 3356,
 'birthday': 1375,
 'vikky': 7293,
 'sindu': 6165,
 'got': 3220,
 'job': 3842,
 'in': 3655,
 'birla': 1372,
 'soft': 6280,
 'just': 3886,
 'arrived': 1090,
 'see': 5975,
 'you': 7706,
 'couple': 2048,
 'days': 2194,
 'lt': 4253,
 'sorry': 6322,
 've': 7267,
 'not': 4828,
 'gone': 3200,
 'to': 6938,
 'that': 6813,
 'place': 5222,
 'll': 4164,
 'do': 2387,
 'so': 6275,
 'tomorrow': 6965,
 'really': 5598,
 'usf': 7228,
 'guess': 3291,
 'might': 4475,
 'as': 1099,
 'well': 7459,
 'take': 6689,
 'car': 1661,
 'please': 5245,
 'charge': 1745,
 'my': 4666,
 'mobile': 4544,
 'when': 7484,
 'get': 3137,
 'up': 7186,
 'morning': 4589,
 'it': 3770,
 'reassuring': 5607,
 'this': 6856,
 'crazy': 2072,
 'world': 7601,
 'although': 943,
 'told': 6954,
 'dat': 2183,
 'into': 3728,
 'baig': 1218,
 'face': 2753,
 'watches': 7404,
 'now': 4841,
 'but': 1587,
 'like': 4117,
 'watch': 7402,
 'gave': 3105,
 'cos': 2028,
 'fr': 2987,
 'thanx': 6811,
 'everything': 2686,
 'done': 2420,
 'today': 6943,
 'touched': 7002,
 'enjoy': 2609,
 'ur': 7205,
 'life': 4106,
 'good': 3204,
 'night': 4771,
 'yeah': 7680,
 'think': 6847,
 'usual': 7233,
 'guy': 3303,
 'still': 6479,
 'passed': 5096,
 'out': 5006,
 'from': 3038,
 'last': 4034,
 'if': 3616,
 'ahold': 887,
 'anybody': 1009,
 'let': 4092,
 'me': 4409,
 'know': 3969,
 'and': 976,
 'throw': 6877,
 'down': 2441,
 'already': 938,
 'one': 4938,
 'loving': 4240,
 'depends': 2267,
 'how': 3537,
 'would': 7613,
 'be': 1286,
 'treated': 7036,
 'whatever': 7479,
 'lol': 4188,
 'what': 7478,
 'mean': 4412,
 'was': 7395,
 'left': 4074,
 'too': 6978,
 'early': 2515,
 'check': 1767,
 'working': 7598,
 'text82228': 6789,
 'more': 4585,
 'ringtones': 5780,
 'logos': 4186,
 'games': 3085,
 'www': 7641,
 'txt82228': 7103,
 'com': 1908,
 'questions': 5519,
 'info': 3686,
 'co': 1876,
 'uk': 7128,
 'is': 3759,
 'running': 5843,
 'am': 948,
 'maybe': 4403,
 'all': 925,
 'are': 1063,
 'feeling': 2818,
 'same': 5882,
 'or': 4971,
 'have': 3378,
 'admit': 833,
 'mad': 4301,
 'then': 6828,
 'where': 7488,
 'correction': 2024,
 'call': 1619,
 'keep': 3919,
 'with': 7551,
 'may': 4401,
 'also': 941,
 'lets': 4093,
 'run': 5842,
 'hey': 3441,
 'mate': 4384,
 'spoke': 6395,
 'mag': 4309,
 'people': 5142,
 'we': 7423,
 're': 5579,
 'on': 4934,
 'deliver': 2247,
 'by': 1603,
 'end': 2594,
 'month': 4578,
 '24th': 372,
 'sept': 6013,
 'talk': 6697,
 'later': 4038,
 'free2day': 2999,
 'sexy': 6033,
 'st': 6424,
 'george': 3133,
 'pic': 5195,
 'jordan': 3862,
 'txt': 7100,
 '89080': 718,
 'dont': 2422,
 'miss': 4513,
 'every': 2678,
 'wk': 7560,
 'saucy': 5907,
 'celeb': 1714,
 'pics': 5200,
 'pocketbabe': 5274,
 '0870241182716': 82,
 'who': 7499,
 'first': 2883,
 'time': 6904,
 'created': 2075,
 'web': 7432,
 'page': 5046,
 'asjesus': 1106,
 'read': 5585,
 'wrote': 7630,
 'waiting': 7359,
 'for': 2951,
 'your': 7710,
 'opinions': 4962,
 'want': 7381,
 'friend': 3021,
 'darlin': 2176,
 'can': 1641,
 'pick': 5196,
 'at': 1132,
 'college': 1903,
 'tell': 6756,
 'wen': 7462,
 'mt': 4627,
 'love': 4230,
 'pete': 5168,
 'xx': 7656,
 'had': 3314,
 'been': 1307,
 'hoping': 3514,
 'send': 6001,
 'message': 4458,
 'rent': 5694,
 'due': 2491,
 'enough': 2614,
 'reserves': 5725,
 'completely': 1940,
 'its': 3778,
 'loan': 4170,
 'need': 4726,
 'could': 2039,
 'her': 3433,
 'balance': 1223,
 'gt': 3282,
 'there': 6834,
 'way': 7418,
 'till': 6902,
 'mid': 4471,
 'march': 4357,
 'hope': 3506,
 'pay': 5115,
 'back': 1209,
 'aight': 891,
 'some': 6290,
 'open': 4954,
 'before': 1311,
 'tonight': 6973,
 'yes': 7692,
 'office': 4899,
 'da': 2152,
 'supposed': 6619,
 'meet': 4428,
 'discuss': 2362,
 'abt': 776,
 'our': 5003,
 'trip': 7045,
 'thought': 6866,
 'xuhui': 7655,
 'afternoon': 865,
 'go': 3179,
 'lesson': 4090,
 'after': 863,
 'attend': 1144,
 'driving': 2468,
 'times': 6905,
 'which': 7493,
 'technical': 6746,
 'support': 6616,
 'voice': 7318,
 'process': 5421,
 'networking': 4749,
 'field': 2838,
 'words': 7593,
 'ym': 7700,
 'tm': 6928,
 'very': 7277,
 'smart': 6237,
 'move': 4605,
 'slave': 6208,
 'smiles': 6247,
 'drink': 2460,
 'coffee': 1886,
 'await': 1178,
 'no': 4790,
 'new': 4754,
 'bar': 1241,
 'airport': 896,
 'satsgettin': 5905,
 '47per': 511,
 'hour': 3530,
 'means': 4416,
 'lie': 4104,
 'touch': 7001,
 'hungry': 3569,
 'gay': 3106,
 'guys': 3304,
 '08718730555': 147,
 '10p': 267,
 'min': 4486,
 'stop': 6492,
 'texts': 6799,
 '08712460324': 110,
 'ask': 1107,
 'iouri': 3742,
 'story': 6504,
 'ten': 6766,
 'hello': 3419,
 'beautiful': 1292,
 'ok': 4915,
 'kinda': 3952,
 'ad': 818,
 'row': 5818,
 'wiv': 7558,
 'he': 3388,
 'walked': 7366,
 'pub': 5473,
 'wanted': 7383,
 'hmmm': 3476,
 'said': 5868,
 'hours': 3531,
 'late': 4036,
 'should': 6112,
 'punish': 5482,
 'she': 6063,
 'dun': 2496,
 'believe': 1323,
 'leh': 4079,
 'tot': 6998,
 'true': 7054,
 'thk': 6857,
 'muz': 4663,
 'us': 7218,
 'tog': 6946,
 'will': 7522,
 'once': 4936,
 'home': 3494,
 'uploaded': 7197,
 'mine': 4491,
 'facebook': 2754,
 'sounds': 6334,
 'talents': 6696,
 'dinner': 2339,
 'date': 2185,
 'next': 4762,
 'week': 7444,
 'delhi': 2245,
 'chennai': 1781,
 'silent': 6152,
 'around': 1084,
 'half': 3324,
 'owe': 5029,
 'either': 2565,
 'works': 7600,
 'years': 7682,
 'old': 4927,
 'doesnt': 2399,
 'bother': 1456,
 'mum': 4643,
 'lor': 4208,
 'reach': 5580,
 'worse': 7607,
 'yar': 7673,
 'they': 6841,
 'say': 5915,
 'error': 2644,
 'didn': 2313,
 'post': 5318,
 'other': 4996,
 'ritten': 5786,
 'stuff': 6538,
 'sit': 6179,
 'angry': 982,
 'hit': 3464,
 'wasn': 7397,
 'checked': 1769,
 'phone': 5181,
 'sleep': 6209,
 'were': 7468,
 'bored': 1447,
 'why': 7506,
 'wouldn': 7615,
 'clean': 1844,
 'fold': 2930,
 'laundry': 4046,
 'etc': 2660,
 'least': 4068,
 'make': 4329,
 'bed': 1300,
 'usually': 7234,
 'body': 1426,
 'takes': 6692,
 'care': 1666,
 'buy': 1592,
 'making': 4333,
 'sure': 6623,
 'progress': 5432,
 'pls': 5252,
 'continue': 1995,
 'saturday': 5906,
 'reaching': 5582,
 'reading': 5588,
 'text': 6788,
 'sent': 6009,
 'meant': 4417,
 'joke': 3853,
 'light': 4113,
 'having': 3383,
 'any': 1008,
 'movies': 4609,
 'laptop': 4027,
 'msgs': 4625,
 'imma': 3638,
 'come': 1913,
 'over': 5022,
 'cause': 1701,
 'jay': 3810,
 'wants': 7385,
 'drugs': 2475,
 'nah': 4677,
 'straight': 6507,
 'bring': 1519,
 'bud': 1554,
 'drinks': 2463,
 'something': 6299,
 'actually': 817,
 'little': 4155,
 'useful': 7224,
 'than': 6802,
 'cash': 1686,
 'problem': 5415,
 'renewal': 5692,
 'right': 5769,
 'away': 1183,
 'his': 3462,
 'details': 2290,
 'pandy': 5060,
 'joined': 3851,
 '4w': 536,
 'technologies': 6747,
 'chikku': 1796,
 'cell': 1718,
 'thts': 6885,
 'nt': 4847,
 'able': 767,
 'reply': 5707,
 'msg': 4619,
 'dad': 2156,
 'contract': 1997,
 '11': 270,
 'mnths': 4539,
 'latest': 4039,
 'motorola': 4601,
 'nokia': 4800,
 'free': 2998,
 'double': 2434,
 'mins': 4500,
 'orange': 4974,
 'tariffs': 6710,
 'callback': 1622,
 'remove': 5689,
 'records': 5631,
 'urgent': 7208,
 'number': 4854,
 'has': 3365,
 'awarded': 1182,
 '2000': 352,
 'prize': 5408,
 'guaranteed': 3286,
 '09058094455': 174,
 'land': 4014,
 'line': 4129,
 'claim': 1832,
 '3030': 438,
 'valid': 7250,
 '12hrs': 289,
 'only': 4944,
 '500': 541,
 'bonus': 1432,
 'caller': 1626,
 '27': 381,
 '03': 14,
 'final': 2861,
 'attempt': 1142,
 'contact': 1987,
 '08714714011': 120,
 'hmm': 3475,
 'stay': 6455,
 'an': 971,
 'eye': 2746,
 'sore': 6319,
 'thing': 6845,
 'haunt': 3374,
 'sorted': 6325,
 'im': 3632,
 'going': 3191,
 'sound': 6332,
 'anyway': 1019,
 'promoting': 5442,
 'hex': 3440,
 'aiyo': 901,
 'bit': 1377,
 'pai': 5048,
 'seh': 5985,
 'noe': 4794,
 'scared': 5925,
 'rem': 5675,
 'die': 2316,
 'hee': 3410,
 'become': 1297,
 'better': 1345,
 'lookin': 4199,
 'oredi': 4982,
 'yrs': 7721,
 'difficult': 2326,
 'those': 6863,
 'ducking': 2487,
 'chinchillas': 1806,
 'mind': 4489,
 'happened': 3349,
 'uncomfortable': 7145,
 'gonna': 3202,
 'deleted': 2244,
 'hot': 3525,
 'live': 4156,
 'fantasies': 2785,
 '08707509020': 90,
 '20p': 361,
 'per': 5144,
 'ntt': 4849,
 'ltd': 4254,
 'po': 5259,
 'box': 1466,
 '1327': 293,
 'croydon': 2094,
 'cr9': 2060,
 '5wb': 568,
 '0870': 72,
 '11mths': 276,
 'update': 7191,
 'oranges': 4975,
 'colour': 1905,
 'camera': 1638,
 'mobiles': 4545,
 'unlimited': 7176,
 'weekend': 7446,
 'calls': 1633,
 'upd8': 7189,
 'freefone': 3002,
 '08000839402': 51,
 '2stoptxt': 423,
 'give': 3163,
 'him': 3455,
 'important': 3645,
 'customer': 2136,
 'service': 6020,
 'announcement': 991,
 'freephone': 3006,
 '0800': 48,
 '542': 558,
 '0825': 63,
 '83039': 667,
 '62735': 583,
 '450': 504,
 'break': 1500,
 'accommodationvouchers': 791,
 'terms': 6774,
 'conditions': 1960,
 'apply': 1041,
 'mustprovide': 4661,
 '15541': 315,
 'boo': 1433,
 'moms': 4565,
 'tortilla': 6995,
 'soup': 6336,
 'yummmm': 7723,
 'year': 7681,
 'princess': 5398,
 'bec': 1294,
 'temple': 6765,
 'na': 4674,
 'hottest': 3529,
 'getting': 3145,
 'wet': 7475,
 'wanting': 7384,
 '89555': 722,
 'costs': 2032,
 '150p': 307,
 'textoperator': 6797,
 'g696ga': 3075,
 '18': 322,
 'xxx': 7658,
 'family': 2778,
 'happiness': 3355,
 'stability': 6425,
 'tranquility': 7017,
 'vibrant': 7281,
 'colourful': 1906,
 'corporation': 2021,
 'outside': 5017,
 'gap': 3090,
 'itself': 3779,
 'taking': 6694,
 'turns': 7087,
 'friends': 3022,
 'staying': 6457,
 'whole': 7501,
 'show': 6119,
 'won': 7580,
 'til': 6901,
 'feel': 2816,
 'ahead': 883,
 'smoke': 6251,
 'worth': 7609,
 'unsubscribe': 7183,
 'yet': 7695,
 'mob': 4542,
 'offer': 4895,
 'package': 5042,
 'term': 6773,
 '54': 557,
 'weeks': 7449,
 'resubmit': 5741,
 'request': 5714,
 'expiry': 2732,
 'themob': 6827,
 'help': 3422,
 'hi': 3444,
 'nice': 4765,
 'cant': 1653,
 'wait': 7356,
 'fran': 2989,
 'ps': 5465,
 'dirty': 2349,
 'anal': 973,
 'sex': 6030,
 '10': 256,
 'man': 4339,
 'gang': 3089,
 'bang': 1231,
 'seriously': 6017,
 'spell': 6370,
 'name': 4683,
 'doing': 2408,
 'test': 6782,
 'earlier': 2513,
 'appreciate': 1045,
 'urself': 7217,
 'tmr': 6932,
 'yup': 7729,
 'long': 4193,
 'since': 6163,
 'screamed': 5946,
 'flaked': 2896,
 'shit': 6087,
 'goin': 3189,
 'roommate': 5807,
 'sir': 6174,
 'letter': 4094,
 'leave': 4069,
 'hop': 3505,
 'ard': 1062,
 'ya': 7666,
 'liao': 4097,
 'stuck': 6528,
 'middle': 4472,
 'hand': 3332,
 'side': 6142,
 'handsome': 3337,
 'finding': 2866,
 'being': 1322,
 'lazy': 4053,
 'towards': 7005,
 'net': 4743,
 'mummy': 4645,
 'boytoy': 1486,
 'does': 2397,
 'dog': 2400,
 'must': 4658,
 'always': 946,
 'word': 7592,
 'did': 2312,
 'alright': 939,
 'omw': 4933,
 'gotta': 3225,
 'change': 1736,
 'order': 4978,
 'half8th': 3325,
 'length': 4083,
 'top': 6986,
 'shorter': 6107,
 'fringe': 3027,
 'wan': 7376,
 'distract': 2370,
 'found': 2980,
 'diff': 2321,
 'farm': 2789,
 'shop': 6098,
 'cheese': 1778,
 'tel': 6752,
 'wats': 7413,
 'add': 820,
 'don': 2418,
 'dude': 2488,
 'fuck': 3048,
 'off': 4891,
 'money': 4569,
 'drive': 2465,
 'sch': 5929,
 'gals': 3083,
 'wanna': 7379,
 'nìte': 4872,
 'nothing': 4833,
 'spl': 6387,
 'wat': 7401,
 'whr': 7505,
 'ru': 5830,
 'seems': 5982,
 'special': 6358,
 'sight': 6145,
 'few': 2832,
 'remain': 5676,
 'maintain': 4326,
 'them': 6824,
 'ends': 2599,
 'sh': 6037,
 'jas': 3807,
 'bloomberg': 1412,
 'center': 1720,
 '447797706009': 501,
 'future': 3071,
 'http': 3551,
 'careers': 1670,
 'use': 7222,
 'soc': 6276,
 'dunno': 2498,
 'type': 7114,
 'ar': 1058,
 'fucking': 3051,
 'chickened': 1793,
 'messaged': 4459,
 'woould': 7590,
 'buzz': 1598,
 'hear': 3398,
 'these': 6836,
 'shirts': 6086,
 'wear': 7428,
 'nudist': 4852,
 'themed': 6825,
 'mu': 4634,
 'doc': 2390,
 'shirt': 6085,
 'hubby': 3553,
 'fiting': 2888,
 'ones': 4939,
 'budget': 1556,
 'load': 4168,
 'card': 1662,
 'abi': 764,
 'hw': 3584,
 'posted': 5321,
 'luv': 4268,
 'mj': 4530,
 'ugh': 7123,
 'outta': 5021,
 'class': 1838,
 'paragon': 5070,
 'havent': 3381,
 'decided': 2214,
 'whether': 7492,
 'cut': 2140,
 'cinema': 1827,
 'plus': 5255,
 'appeal': 1035,
 'tomo': 6963,
 'thriller': 6874,
 'director': 2345,
 'mac': 4293,
 '30': 433,
 'welp': 7461,
 'sort': 6323,
 'semiobscure': 5999,
 'internet': 3724,
 'frm': 3028,
 'matter': 4392,
 'haha': 3316,
 'most': 4594,
 'forfeit': 2958,
 'snowboarding': 6272,
 'wondering': 7584,
 'planning': 5232,
 'everyone': 2683,
 'together': 6947,
 'befor': 1310,
 'greet': 3261,
 'kind': 3951,
 'affair': 853,
 'cheers': 1776,
 'entry': 2626,
 '250': 374,
 'weekly': 7448,
 'comp': 1927,
 'enter': 2616,
 '84128': 681,
 'textcomp': 6793,
 'cust': 2133,
 '08712405020': 108,
 'de': 2199,
 'went': 7465,
 'dear': 2204,
 'voucher': 7328,
 'holder': 3487,
 'meal': 4410,
 'following': 2935,
 'link': 4135,
 'pc': 5125,
 'dining': 2338,
 'experiencehttp': 2727,
 'vouch4me': 7327,
 'etlp': 2662,
 'asp': 1115,
 'cbe': 1706,
 'logo': 4183,
 'lover': 4235,
 'names': 4687,
 'heart': 3402,
 'name1': 4684,
 'name2': 4685,
 'mobno': 4549,
 'eg': 2554,
 'adam': 819,
 'eve': 2669,
 '07123456789': 25,
 '87077': 699,
 'yahoo': 7668,
 'pobox36504w45wq': 5266,
 'txtno': 7107,
 'ads': 840,
 'thats': 6816,
 'leaving': 4071,
 'soon': 6313,
 'rofl': 5796,
 'betta': 1344,
 'invest': 3734,
 'anti': 1006,
 'aging': 878,
 'products': 5424,
 'detroit': 2292,
 'snow': 6271,
 'wendy': 7463,
 'costa': 2030,
 'del': 2240,
 'sol': 6284,
 'holiday': 3490,
 '5000': 542,
 'collection': 1901,
 '09050090044': 166,
 'toclaim': 6942,
 'sae': 5861,
 'tc': 6729,
 'pobox334': 5265,
 'stockport': 6484,
 'sk38xh': 6191,
 'cost': 2029,
 '50': 540,
 'pm': 5258,
 'max10mins': 4397,
 'helens': 3416,
 'fone': 2939,
 'princes': 5397,
 'nite': 4783,
 'tb': 6727,
 'kate': 3911,
 'practising': 5348,
 'curtsey': 2131,
 'sweets': 6655,
 'slept': 6216,
 'thinkthis': 6852,
 'dangerous': 2170,
 'cocksuckers': 1884,
 'makes': 4330,
 'ipads': 3746,
 'worthless': 7610,
 'garbage': 3093,
 'novelty': 4839,
 'items': 3773,
 'bad': 1212,
 'even': 2671,
 'tht': 6884,
 'incident': 3660,
 'stock': 6482,
 'talking': 6699,
 'about': 769,
 'hen': 3430,
 'swing': 6659,
 'watching': 7406,
 'olave': 4925,
 'mandara': 4347,
 'movie': 4608,
 'kano': 3906,
 'trishul': 7047,
 'theatre': 6819,
 'wit': 7550,
 'frnds': 3031,
 'honey': 3499,
 'missing': 4517,
 'searching': 5958,
 'dual': 2483,
 'sim': 6156,
 'pa': 5039,
 'wife': 7513,
 'knew': 3966,
 'murder': 4651,
 'exactly': 2701,
 'compass': 1931,
 'map': 4354,
 'soul': 6331,
 'guide': 3296,
 'never': 4753,
 'loose': 4205,
 'gnun': 3178,
 'via': 7280,
 'way2sms': 7419,
 'mystery': 4671,
 'solved': 6289,
 'opened': 4955,
 'email': 2580,
 'another': 995,
 'batch': 1260,
 'isn': 3765,
 'sweetie': 6654,
 'mila': 4478,
 'age23': 873,
 'blonde': 1408,
 'look': 4197,
 'fun': 3059,
 'mtalk': 4628,
 '69866': 598,
 '30pp': 442,
 '1st': 339,
 '5free': 561,
 'increments': 3672,
 'help08718728876': 3425,
 'jst': 3871,
 'tat': 6715,
 'wont': 7586,
 'belive': 1324,
 'god': 3185,
 'jesus': 3830,
 'japanese': 3806,
 'proverb': 5458,
 'none': 4807,
 'indian': 3678,
 'version': 7276,
 'finally': 2862,
 'kerala': 3927,
 'strike': 6517,
 'against': 870,
 'beauty': 1293,
 'pimples': 5212,
 'exact': 2700,
 'intentions': 3717,
 'lovin': 4239,
 'opposite': 4965,
 'dropped': 2471,
 'awesome': 1184,
 'restocked': 5740,
 'round': 5814,
 'certainly': 1725,
 'puts': 5499,
 'things': 6846,
 'perspective': 5165,
 'happens': 3351,
 'forgot': 2964,
 'smth': 6262,
 'sections': 5971,
 'clearer': 1848,
 'fall': 2771,
 'quite': 5524,
 'prone': 5446,
 'falls': 2774,
 'lucky': 4259,
 'fetch': 2829,
 'ill': 3628,
 'says': 5919,
 'ass': 1117,
 'south': 6339,
 'tampa': 6705,
 'preferably': 5365,
 'kegger': 3922,
 'addie': 824,
 'amp': 966,
 'art': 1093,
 'here': 3434,
 'okie': 4920,
 'pin': 5213,
 'spoons': 6401,
 'okay': 4916,
 'schedule': 5930,
 'town': 7006,
 'awake': 1180,
 'kiss': 3958,
 'finish': 2871,
 'person': 5160,
 'sms': 6257,
 'survey': 6633,
 'okies': 4921,
 'yan': 7672,
 'jiu': 3838,
 'skip': 6199,
 'oso': 4994,
 ...}

In [38]:
# Now let us train our ML model with the training data 
# We are using Naive Bayes Classifier also in that we are using MultinomialNB where NB stands for Naive Bayes

from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv,y_train) # Now our model is trained so we test that.

MultinomialNB()

In [39]:
# First let's also convert X_test into X_test_cv
X_test_cv = v.transform(X_test)
X_test_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(1115, 7744))

In [40]:
# Now testing our model and Compare the results using classification_report

from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test,y_pred)) # First providing the Actual truth i.e y_test and then Our predicted result y_pred

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       978
           1       0.96      0.94      0.95       137

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115

In [41]:
# Testing on self examples
emails = [
    "Hey Mohan, Can we get together to watch cricket tommorow",
    'Upto 20\\% discount on credit cards,Exclusively for you Hurry Up to grab the deal'
]

email_cv = v.transform(emails)

model.predict(email_cv) # array([0, 1]) -> It means first one is Ham and 2nd one is Spam

array([0, 1])

# Differ bw  fit , transform and fit_transform

In [42]:
# fit() -> LEARN = makes the object learn the required information/pattern from the data
# Example when we using in Bag of Word
v.fit(X_train) # CountVectorizer looks at X_train and learns the vocabulary.

# But fit() doesn't convert the sentences into numbers.

X_train_cv = v.transform(X_train) # transform()= CONVERT = takes data and converts it according to what was learned during fit().
# The previously learned vocabulary is used to convert text into numerical vectors.
print(X_train_cv.toarray())

# fit_transform() = LEARN + CONVERT =  It performs both operations together:
v.fit_transform(X_train) # Instead of seperately doing do it at once

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59460 stored elements and shape (4457, 7744)>

# We use fit_transform() for Training Data and transform() on Test Data ? Why?

We want the vectorizer to:

* Learn vocabulary from training data.
* Convert training data into numerical form.

so, X_train -> fit -> Learn vocabulary -> transform -> Numerical data

And for the test data we are using X_test_cv = v.transform(X_test) bcz
* We don't want to learn anything from the test data.
* The test data should be treated as unseen data.

In [43]:
# Complete Example of Bag Of Word
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

v = CountVectorizer()

# Training
X_train_cv = v.fit_transform(X_train)

# Train model
model = MultinomialNB()
model.fit(X_train_cv, y_train)

# Testing
X_test_cv = v.transform(X_test)

# Prediction
y_pred = model.predict(X_test_cv)

# Now Instead of doing all of this manually we can use sklearn.pipeline to Done whole procedure

In [ ]:
from sklearn.pipeline import Pipeline

clf = Pipeline([ # clf is the name of the variable stands for classifer and we can give any name.
    ('vectorizer',CountVectorizer()), # The first one is the name of the step (We can give any name here instead of vectorizer) and the second one is the Object of what we need to give to the pipeline
    ('nb',MultinomialNB())
])

clf.fit(X_train,y_train) # This time we don't need to provide the X_train_cv as The CountVectorizer in the pipeline will handle the same and convert it into vectors automatically and feed that into our ML model in the next step of the pipeline

y_pred_clf = clf.predict(X_test)
print(classification_report(y_test,y_pred_clf))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       978
           1       0.96      0.94      0.95       137

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115